callbacks:
  list:
  - earlystop
  metrics:
  - val_loss
  - val_roc
  - train_loss
  mode: max
  monitor: val_roc
  patience: 5
  write_grads: false
data:
  T_max: 1000.0
  T_min_warn: 30
  T_warning: 1.024
  augment_during_training: false
  augmentation_mode: none
  bleed_in: 0
  bleed_in_equalize_sets: false
  bleed_in_remove_from_test: true
  bleed_in_repeat_fac: 1
  current_end_thresh: 10000
  current_index: 0
  current_thresh: 750000
  cut_shot_ends: true
  dt: 0.001
  equalize_classes: false
  floatx: float32
  norm_stat_range: 100.0
  normalizer: var
  plotting: false
  positive_example_penalty: 5.0
  recompute: false
  recompute_normalization: false
  signal_to_augment: None
  use_shots: 6000
  window_decay: 2
  window_size: 10
env:
  name: frnn
  type: anaconda
fs_path: /tigress
model:
  backend: tensorflow
  clipnorm: 10.0
  dense_regularization: 0.001
  dense_size: 128
  dropout_prob: 0.1
  extra_dense_input: false
  ignore_timesteps: 100
  length: 128
  loss_scale_factor: 1.0
  lr: 0.00017
  lr_decay: 0.98
  num_conv_filters: 128
  num_conv_layers: 3
  optimizer: adam
  pool_size: 2
  pred_batch_size: 128
  pred_length: 200
  regularization: 0.001
  return_sequences: true
  rnn_layers: 2
  rnn_size: 100
  rnn_type: LSTM
  shallow: false
  shallow_model:
    C: 1.0
    final_hidden_layer_size: 10
    kernel: rbf
    learning_rate: 0.1
    learning_rate_mlp: 0.0001
    max_depth: 3
    mlp_regularization: 0.0001
    n_estimators: 100
    num_hidden_layers: 3
    num_samples: 1000000
    scale_pos_weight: 10.0
    skip_train: false
    type: xgboost
  size_conv_filters: 3
  skip: 1
  stateful: true
  use_batch_norm: false
  use_bidirectional: false
  warmup_steps: 0
num_gpus: 4
paths:
  data: jet_data
  executable: mpi_learn_arg.py
  shallow_executable: learn.py
  shot_list_dir: /shot_lists/
  signal_prepath: /signal_data/
  specific_signals:
  - li
  - ip
  - energy
  - lm
  - dens
  - pradcore
  - pradedge
  - pradtot
  - pin
  - energydt
  tensorboard_save_path: /Graph/
target: hinge
training:
  as_array_of_shots: true
  batch_generator_warmup_steps: 0
  batch_size: 256
  data_parallel: false
  hyperparam_tuning: false
  max_patch_length: 100000
  num_batches_minimum: 10
  num_epochs: 4
  num_shots_at_once: 200
  ranking_difficulty_fac: 1.0
  shuffle_training: true
  train_frac: 0.66
  use_mock_data: false
  validation_frac: 0.33
